import { getGroqClient } from './groq'
import { getSupabaseClient } from './supabase'
import { getEmbedding } from './embeddings'
import { TableClassification } from './types'

export async function classifySchema(schema: string): Promise<TableClassification[]> {
  const groq = getGroqClient()
  const completion = await groq.chat.completions.create({
    model: 'llama-3.3-70b-versatile',
    temperature: 0.1,
    messages: [
      {
        role: 'user',
        content: `Analyze this SQL schema and classify each table for RLS policy generation.

For each table identify:
- ownershipColumn: the column linking rows to a user (user_id, owner_id, created_by) or null if none
- pattern: one of "basic-ownership", "multi-tenant", "public-read-private-write", "admin-bypass", "join-based", "insert-only", "profiles", "authenticated-only"
- sensitivity: "public", "private", or "admin-only"

Respond ONLY with a valid JSON array. No explanation, no markdown, no backticks.

Example:
[{"table":"posts","ownershipColumn":"user_id","pattern":"basic-ownership","sensitivity":"private"}]

SCHEMA:
${schema}`,
      },
    ],
  })

  const raw = completion.choices[0]?.message?.content?.trim() ?? '[]'
  try {
    return JSON.parse(raw) as TableClassification[]
  } catch {
    return []
  }
}

export async function retrievePatterns(classifications: TableClassification[]): Promise<string> {
  const supabase = getSupabaseClient()
  const allDocs: string[] = []

  for (const table of classifications) {
    const query = `${table.pattern} RLS policy ${table.sensitivity} table ${table.ownershipColumn ?? 'no ownership column'}`
    const embedding = await getEmbedding(query)

    const { data } = await supabase.rpc('match_rls_docs', {
      query_embedding: embedding,
      match_count: 2,
    })

    if (data?.length) {
      allDocs.push(`--- Relevant pattern for table "${table.table}" ---\n${data.map((d: { content: string }) => d.content).join('\n\n')}`)
    }
  }

  return allDocs.join('\n\n')
}

export async function generatePolicies(
  schema: string,
  classifications: TableClassification[],
  retrievedDocs: string
): Promise<string> {
  const groq = getGroqClient()
  const completion = await groq.chat.completions.create({
    model: 'llama-3.3-70b-versatile',
    temperature: 0.1,
    messages: [
      {
        role: 'user',
        content: `You are a Supabase RLS expert. Generate a complete migration file based on the schema, table classifications, and reference patterns below.

STRICT RULES:
- Output ONLY valid PostgreSQL SQL. No markdown, no backticks, no explanations.
- Start with: -- Migration: rls_policies (generated by PainkillerRLS)
- ENABLE ROW LEVEL SECURITY on every table
- Create policies for SELECT, INSERT, UPDATE, DELETE on every table
- Use USING() for SELECT and DELETE, WITH CHECK() for INSERT and UPDATE
- Use auth.uid() for ownership checks
- Add a comment above each table section

SCHEMA:
${schema}

TABLE CLASSIFICATIONS:
${JSON.stringify(classifications, null, 2)}

REFERENCE PATTERNS FROM KNOWLEDGE BASE:
${retrievedDocs}`,
      },
    ],
  })

  return completion.choices[0]?.message?.content?.trim() ?? ''
}

export async function validatePolicies(policies: string, schema: string): Promise<string> {
  const groq = getGroqClient()
  const completion = await groq.chat.completions.create({
    model: 'llama-3.3-70b-versatile',
    temperature: 0.1,
    messages: [
      {
        role: 'user',
        content: `You are a Supabase RLS security reviewer. Review the generated RLS policies against the original schema.

STRICT RULES FOR VALID SUPABASE RLS:
- SELECT → needs USING() only
- INSERT → needs WITH CHECK() only  
- UPDATE → needs BOTH USING() and WITH CHECK() — this is the most common mistake
- DELETE → needs USING() only
- Every table must have all 4 operations covered
- auth.uid() = id is correct for profiles table, NOT auth.role() IS NOT NULL

If everything is correct, return the policies unchanged.
If you find ANY issue, return the fully CORRECTED version.

Output ONLY valid PostgreSQL SQL. No explanation, no markdown, no backticks.

ORIGINAL SCHEMA:
${schema}

GENERATED POLICIES:
${policies}`,
      },
    ],
  })

  return completion.choices[0]?.message?.content?.trim() ?? policies
}

export async function* runPipelineGenerator(schema: string) {
  yield { step: 1, status: 'running', label: 'Classifying tables' }
  const classifications = await classifySchema(schema)
  yield { step: 1, status: 'done', label: 'Classifying tables' }

  yield { step: 2, status: 'running', label: 'Retrieving RLS patterns' }
  const retrievedDocs = await retrievePatterns(classifications)
  yield { step: 2, status: 'done', label: 'Retrieving RLS patterns' }

  yield { step: 3, status: 'running', label: 'Generating policies' }
  const policies = await generatePolicies(schema, classifications, retrievedDocs)
  yield { step: 3, status: 'done', label: 'Generating policies' }

  yield { step: 4, status: 'running', label: 'Validating output' }
  const validated = await validatePolicies(policies, schema)
  yield { step: 4, status: 'done', label: 'Validating output' }

  yield { type: 'result', migration: validated }
}